# SPDX-License-Identifier: GPL-2.0+

nandcore-objs := core.o bbt.o
obj-$(CONFIG_MTD_NAND_CORE) += nandcore.o
obj-$(CONFIG_MTD_SPI_NAND) += spi/
obj-$(CONFIG_NAND_NUC970) += nuc970_nand.o
obj-$(CONFIG_NAND_NUC980) += nuc980_nand.o
